# Generated by Django 4.2.1 on 2023-06-15 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_taggs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='taggs',
            new_name='tags',
        ),
    ]
